heat_template_version: queens
description: AutoScaling Flask App
parameters:
  image:
    type: string
    description: Image used for servers
    default: ubuntu-docker
  key:
    type: string
    description: SSH key to connect to the servers
    default: controller21
  flavor:
    type: string
    description: flavor used by the web servers
    default: m1.mini2
  lb_network:
    type: string
    description: Network used by the lb server
    default: vlan135
  asg_network:
    type: string
    description: Network used by the server
    default: mgnt-net-194
  lb_subnet_id:
    type: string
    description: subnet on which the load balancer will be located
    default: 4407e64d-36f3-44e0-b0c1-73a3f0292856
  asg_subnet_id:
    type: string
    description: subnet on which the asg instance will be located
    default: 0326e578-a4c2-4e93-8ca0-e904000b68fe
  external_network_id:
    type: string
    description: UUID of a Neutron external network
    default: f034514b-c49f-497b-9a0d-06de20b452fc
resources:
  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 3
      resource:
        type: lb_server.yaml
        properties:
          flavor: {get_param: flavor}
          image: {get_param: image}
          key_name: {get_param: key}
          network: {get_param: asg_network}
          subnet: {get_param: asg_subnet_id}
          pool_1_id: {get_resource: pool_1}
          pool_2_id: {get_resource: pool_2}
          metadata: {"metering.server_group": {get_param: "OS::stack_id"}}
  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: 1
  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: -1
  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale up if CPU > 80% for 5 minutes
      metric: cpu_util
      aggregation_method: mean
      granularity: 300
      evaluation_periods: 1
      threshold: 80
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [web_server_scaleup_policy, signal_url]}
      query:
        list_join:
          - ''
          - - {'=': {server_group: {get_param: "OS::stack_id"}}}
  cpu_alarm_low:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale down if CPU < 15% for 5 minutes
      metric: cpu_util
      aggregation_method: mean
      granularity: 300
      evaluation_periods: 1
      threshold: 15
      resource_type: instance
      comparison_operator: lt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [web_server_scaledown_policy, signal_url]}
      query:
        list_join:
          - ''
          - - {'=': {server_group: {get_param: "OS::stack_id"}}}
  lb:
    type: OS::Octavia::LoadBalancer
    properties:
      vip_subnet: { get_param: lb_subnet_id }
  listener:
    type: OS::Octavia::Listener
    properties:
      loadbalancer: { get_resource: lb }
      protocol: HTTP
      protocol_port: 80
  pool_1:
    type: OS::Octavia::Pool
    properties:
      listener: { get_resource: listener }
      loadbalancer: { get_resource: lb }
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      session_persistence:
        type: SOURCE_IP
  pool_2:
    type: OS::Octavia::Pool
    properties:
      listener: { get_resource: listener }
      loadbalancer: { get_resource: lb }
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      session_persistence:
        type: SOURCE_IP
  monitor_1:
    type: OS::Octavia::HealthMonitor
    properties:
      pool: { get_resource: pool_1 }
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
  monitor_2:
    type: OS::Octavia::HealthMonitor
    properties:
      pool: { get_resource: pool_2 }
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
 # assign a floating ip address to the load balancer
  # pool.
  lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}
      port_id: {get_attr: [lb, vip_port_id]}

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaleup_policy, alarm_url]}
  scale_dn_url:
    description: >
      This URL is the webhook to scale down the autoscaling group.
      You can invoke the scale-down operation by doing an HTTP POST to
      this URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaledown_policy, alarm_url]}
  pool_ip_address:
    value: {get_attr: [lb, vip_address]}
    description: The IP address of the load balancing pool
  website_url:
    value:
      str_replace:
        template: http://host/
        params:
          host: { get_attr: [lb_floating, floating_ip_address] }
    description: >
      This URL is the "external" URL that can be used to access the
      Flask app.
  gnocchi_query:
    value:
      str_replace:
        template: >
          gnocchi measures aggregation --resource-type instance
          --query 'server_group="stackval"'
          --granularity 60 --aggregation mean -m cpu_util
        params:
          stackval: { get_param: "OS::stack_id" }
    description: >
      This is a Gnocchi query for statistics on the cpu_util measurements about
      OS::Nova::Server instances in this stack. The --resource-type select the
      type of Gnocchi resource. The --query parameter filters resources
      according to its attributes. When a VM's metadata includes an item of the
      form metering.server_group=X, the corresponding Gnocchi resource has a
      attribute named server_group that can queried with 'server_group="X"' In
      this case the nested stacks give their VMs metadata that is passed as a
      nested stack parameter, and this stack passes a metadata of the form
      metering.server_group=X, where X is this stack's ID.
