heat_template_version: queens

description: Template to spawn an cirros instance

parameters:
  metadata:
    type: json
  image:
    type: string
    description: Name/ID of the image to use for the instance to be created
    default: cirros
    constraints:
      - custom_constraint: glance.image
        description: Must be a image name/id known to Glance.
  flavor:
    type: string
    description: Flavor for the instance to be created.
    default: tiny-baby
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a flavor known to Nova.
  key_name:
    type: string
    description: keypair to be used
    default: kiennt
    constraints:
      - custom_constraint: nova.keypair
        description: Must be a keypair known to Nova
  network:
    type: string
    description: network to attach instance to
    default: mgnt-net-194
    constraints:
      - custom_constraint: neutron.network # Need to choose internal network

resources:
  server:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
        - device_name: vda
          delete_on_termination: true
          volume_id: { get_resource: volume }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      metadata: { get_param: metadata }
      networks:
        - port: { get_resource: port }

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - default

  volume:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: image }
      size: 1
